name: build

on: 
  pull_request:
    paths:
      - 'search/**'
      - 'tests/**'

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint ./search
      - name: Test with pytest
        run: |
          pytest -v --cov=search --cov-report=xml:coverage.xml
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  docker:
    runs-on: ubuntu-latest
    needs: python
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ankursoni/webscrappe-trademe-co-nz-property:mvp
